Updated the about me section and contact form section

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -17,7 +17,7 @@ jobs:
     defaults:
         run:
           shell: bash
-          working-directory: ../src/backend/infra
+          working-directory: ../
 
     env:
         TF_VAR_token: ${{ secrets.GITHUB_TOKEN }}
@@ -25,39 +25,49 @@ jobs:
         AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: ${{ secrets.REGION }}
     
-    steps:
-      - name: Checkout the repo  
-        uses: actions/checkout@v4
+    # steps:
+    #   - name: Checkout the repo  
+    #     uses: actions/checkout@v4
       
-      - name: Set up Terraform CLI
-        uses: hashicorp/setup-terraform@v3
+    #   - name: Set up Terraform CLI
+    #     uses: hashicorp/setup-terraform@v3
 
-      - name: Hello World
-        run: echo "Hello World"
+    #   - name: Hello World
+    #     run: echo "Hello World"
         
-        #test your terraform commands
-      - name: Terraform fmt
-        id: fmt
-        # Run even if formatting fails
-        if: success() || failure()
-        run: terraform fmt -check
-        # continue-on-error: true
+    #     #test your terraform commands
+    #   - name: Terraform fmt
+    #     id: fmt
+    #     # Run even if formatting fails
+    #     if: success() || failure()
+    #     run: terraform fmt -check
+    #     # continue-on-error: true
 
-      - name: Terraform Init
-        id: validate
-        run: terraform validate -no-color
-        env:
-            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-            AWS_DEFAULT_REGION: ${{ secrets.REGION }}
+    #   - name: Terraform Init
+    #     id: validate
+    #     run: terraform validate -no-color
+    #     env:
+    #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+    #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    #         AWS_DEFAULT_REGION: ${{ secrets.REGION }}
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan -auto-approve
-        env:
-            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-            AWS_DEFAULT_REGION: ${{ secrets.REGION }}
+    #   - name: Terraform Plan
+    #     id: plan
+    #     run: terraform plan -auto-approve
+    #     env:
+    #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+    #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    #         AWS_DEFAULT_REGION: ${{ secrets.REGION }}
+
+
+
+
+
+
+
+
+
+
     #   - name: Terraform Apply
         # id: apply
         # run: terraform apply -auto-approve
